run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - test
  skip-files:
    - ".*\\.pb\\.go$"

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/vanducng/cflip
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - lll
    - gosec
    - goconst
    - gocyclo
    - dupl
    - goimports
    - gocritic
    - nakedret
    - exportloopref
    - gocritic
    - gomnd
    - goprintffuncname

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

# golangci.com configuration
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml