version: "2"

linters:
  enable:
    - bodyclose
    - goprintffuncname
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - whitespace
    - gosec
    - goconst
    - gocyclo
    - dupl
    - gocritic
    - errcheck
    - ineffassign
    - unused

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  nolintlint:
    allow-unused: true
    require-explanation: false
    require-specific: false

  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

run:
  timeout: 5m